services:
  api:
    image: desafio-backend
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: desafio_backend
    ports:
      - '5432'